name: svarog
description: News app that fetches data from multiple sources.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  adaptive_theme: ^2.3.0
  html_unescape: ^2.0.0
  cached_network_image: ^3.1.0
  flutter_html: ^2.1.5
  tuple: ^2.0.0
  http: ^0.13.4
  infinite_scroll_pagination: ^3.1.0
  shared_preferences: ^2.0.12
  url_launcher: ^6.0.17
  timeago: ^3.1.0

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_launcher_icons: "^0.9.2"
  flutter_native_splash: ^1.3.1
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: ComicRunes
      fonts:
        - asset: assets/fonts/comic-runes.regular.otf
