name: newsrs
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  adaptive_theme: ^2.3.0
  html_unescape: ^2.0.0
  cached_network_image: ^3.1.0
  flutter_html: ^2.1.5
  tuple: ^2.0.0
  http: ^0.13.4
  timeago: ^3.1.0

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_native_splash: ^1.3.1
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
